// D-08: "book illustration, pen + watercolour" as one full-screen pass (WatercolorFeature).
// 1. Colour is read through a low-frequency warp (the "bleed" of the edges of paint spots) and darkened where it changes (pigment pools at the edge).
// 2. Tone is posterised softly (flat washes instead of a smooth gradient), lifted towards warm paper, granulated by the paper grain.
// 3. Pen line from depth (second difference, so slopes give nothing) and world normals (creases), a constant number of pixels wide,
//    warm dark brown, with the width and the strength varied by the paper.
// 4. Warm grade (blue at night: _ZD_Night from SunController), tonal S-curve, vignette. D-21: thin sepia pen line by silhouettes and facet edges.
// All numbers come from WatercolorSettings; the paper texture is generated by code (PaperTexture).
Shader "Hidden/Zelda/Watercolor"
{
    SubShader
    {
        Tags { "RenderType" = "Opaque" "RenderPipeline" = "UniversalPipeline" }
        ZWrite Off ZTest Always Cull Off Blend Off

        Pass
        {
            Name "Watercolor"

            HLSLPROGRAM
            #pragma target 3.5
            #pragma vertex Vert
            #pragma fragment frag
            #pragma multi_compile_fragment _ _GBUFFER_NORMALS_OCT

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.core/Runtime/Utilities/Blit.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/DeclareDepthTexture.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/DeclareNormalsTexture.hlsl"

            TEXTURE2D(_PaperTex);
            SAMPLER(sampler_PaperTex);

            float4 _LineColor;       // rgb, a = strength
            float4 _LineParams;      // x = width in px, y = depth threshold (m), z = normal threshold, w = wobble 0..1
            float4 _WashParams;      // x = levels, y = posterize 0..1, z = bleed px, w = edge darken
            float4 _PaperParams;     // x = paper tile px, y = grain, z = blotch, w = pigment (0..1: how much of the colour survives over the paper)
            float4 _PaperColor;
            float4 _GradeParams;     // x = saturation, y = contrast, z = vignette strength, w = vignette start
            float4 _WarmTint;
            float4 _VignetteColor;
            float4 _ToneParams;      // x = S-curve strength (lighter lights, deeper shadows)
            float4 _NightTint;       // grade multiplier at night
            float4 _NightPaper;      // paper colour at night
            float4 _NightVignette;
            float _ZD_Night;         // 0 day … 1 night (global, SunController)

            float EyeDepth(float raw)
            {
                #if UNITY_REVERSED_Z
                float d01 = 1.0 - raw;
                #else
                float d01 = raw;
                #endif
                float ortho = _ProjectionParams.y + d01 * (_ProjectionParams.z - _ProjectionParams.y);
                float persp = LinearEyeDepth(raw, _ZBufferParams);
                return unity_OrthoParams.w > 0.5 ? ortho : persp;
            }

            float DepthAt(float2 uv) { return EyeDepth(SampleSceneDepth(uv)); }

            float3 ToGamma(float3 c) { return pow(max(c, 0.0), 1.0 / 2.2); }
            float3 ToLinear(float3 c) { return pow(max(c, 0.0), 2.2); }
            float Luma(float3 c) { return dot(c, float3(0.299, 0.587, 0.114)); }

            half4 frag(Varyings i) : SV_Target
            {
                float2 uv = i.texcoord;
                float2 px = rcp(_ScreenParams.xy);

                // Paper: fine grain (r), blotches (g), two warp fields (b, a).
                float2 paperUv = uv * _ScreenParams.xy / _PaperParams.x;
                float4 paper = SAMPLE_TEXTURE2D(_PaperTex, sampler_PaperTex, paperUv);
                float4 paperBig = SAMPLE_TEXTURE2D(_PaperTex, sampler_PaperTex, paperUv * 0.37 + 0.31);

                // Bleed: the colour is taken from a slightly displaced place; the field is smooth, so edges wobble without noise.
                float2 warp = (float2(paperBig.b, paperBig.a) - 0.5) * 2.0 * _WashParams.z * px;
                float2 wuv = uv + warp;
                float3 src = SAMPLE_TEXTURE2D_X(_BlitTexture, sampler_LinearClamp, wuv).rgb;

                // Pigment pools at the edge of a spot: darken where the colour changes.
                float2 e = px * 1.5;
                float lC = Luma(src);
                float lL = Luma(SAMPLE_TEXTURE2D_X(_BlitTexture, sampler_LinearClamp, wuv - float2(e.x, 0)).rgb);
                float lR = Luma(SAMPLE_TEXTURE2D_X(_BlitTexture, sampler_LinearClamp, wuv + float2(e.x, 0)).rgb);
                float lD = Luma(SAMPLE_TEXTURE2D_X(_BlitTexture, sampler_LinearClamp, wuv - float2(0, e.y)).rgb);
                float lU = Luma(SAMPLE_TEXTURE2D_X(_BlitTexture, sampler_LinearClamp, wuv + float2(0, e.y)).rgb);
                float grad = saturate((abs(lL - lR) + abs(lD - lU)) * 3.0);
                float3 col = ToGamma(src);
                col *= 1.0 - grad * _WashParams.w;

                // Soft posterisation of tone, chroma kept.
                float luma = max(Luma(col), 1e-3);
                float t = luma * _WashParams.x + (paper.g - 0.5) * _PaperParams.z * 1.5; // paper breaks the straight band borders (D-21: gently, no clouds)
                float f = floor(t);
                float q = (f + smoothstep(0.3, 0.7, t - f)) / _WashParams.x;
                col *= lerp(luma, q, _WashParams.y) / luma;

                // Paint over paper: blacks never go fully black; grain and uneven washes.
                float3 paperCol = lerp(_PaperColor.rgb, _NightPaper.rgb, _ZD_Night);
                col = lerp(paperCol * saturate(col * 1.05), col, _PaperParams.w);
                col *= 1.0 - (1.0 - paper.r) * _PaperParams.y;
                col *= 1.0 + (paper.g - 0.5) * _PaperParams.z;

                // Pen line.
                float wob = 1.0 + (paperBig.g - 0.5) * _LineParams.w * 1.6;
                float2 o = px * _LineParams.x * wob;
                float d0 = DepthAt(uv);
                float dL = DepthAt(uv - float2(o.x, 0));
                float dR = DepthAt(uv + float2(o.x, 0));
                float dD = DepthAt(uv - float2(0, o.y));
                float dU = DepthAt(uv + float2(0, o.y));
                // Positive where this pixel is nearer than its surroundings (front side of a silhouette); zero on any plane.
                float lap = max(dL + dR - 2.0 * d0, 0.0) + max(dD + dU - 2.0 * d0, 0.0);
                float depthEdge = smoothstep(_LineParams.y, _LineParams.y * 2.0, lap);

                float3 n0 = SampleSceneNormals(uv);
                float3 nL = SampleSceneNormals(uv - float2(o.x, 0));
                float3 nR = SampleSceneNormals(uv + float2(o.x, 0));
                float3 nD = SampleSceneNormals(uv - float2(0, o.y));
                float3 nU = SampleSceneNormals(uv + float2(0, o.y));
                float nd = 0.0;
                float n0ok = dot(n0, n0) > 0.25 ? 1.0 : 0.0;
                nd = max(nd, (dot(nL, nL) > 0.25 ? 1.0 - dot(n0, nL) : 0.0));
                nd = max(nd, (dot(nR, nR) > 0.25 ? 1.0 - dot(n0, nR) : 0.0));
                nd = max(nd, (dot(nD, nD) > 0.25 ? 1.0 - dot(n0, nD) : 0.0));
                nd = max(nd, (dot(nU, nU) > 0.25 ? 1.0 - dot(n0, nU) : 0.0));
                float normalEdge = smoothstep(_LineParams.z, _LineParams.z * 1.8, nd) * n0ok;

                float line_ = saturate(max(depthEdge, normalEdge * 0.8));
                line_ *= _LineColor.a * (0.8 + 0.2 * paper.r + (paperBig.g - 0.5) * _LineParams.w);
                col = lerp(col, _LineColor.rgb, saturate(line_));

                // Grade: muted, warm; vignette like an old print.
                float g = Luma(col);
                col = lerp(g.xxx, col, _GradeParams.x);
                col = (col - 0.5) * _GradeParams.y + 0.5;
                col = saturate(col);
                col = lerp(col, col * col * (3.0 - 2.0 * col), _ToneParams.x * (1.0 - 0.6 * _ZD_Night));
                col *= lerp(_WarmTint.rgb, _NightTint.rgb, _ZD_Night);
                float2 vv = (uv - 0.5) * float2(_ScreenParams.x / _ScreenParams.y, 1.0) * 1.6;
                float vig = smoothstep(_GradeParams.w, 1.0, length(vv)) * _GradeParams.z;
                col = lerp(col, col * lerp(_VignetteColor.rgb, _NightVignette.rgb, _ZD_Night), vig);

                return half4(ToLinear(saturate(col)), 1.0);
            }
            ENDHLSL
        }
    }
    FallBack Off
}
