using System.IO;
using System.Linq;
using ZeldaDaughter.Core.Scenes;

namespace ZeldaDaughter.Core.Tests
{
    /// <summary>T-04: every scenes/*.json parses and validates — checked on the server before Unity sees it.</summary>
    public class SceneConfigTests
    {
        static string ScenesDir => Path.Combine(Directory.GetParent(TestPaths.CoreRoot)!.FullName, "scenes");

        [Fact]
        public void All_scene_configs_are_valid()
        {
            var files = Directory.GetFiles(ScenesDir, "*.json");
            Assert.NotEmpty(files);
            foreach (var f in files)
            {
                var c = SceneConfig.Parse(File.ReadAllText(f));
                Assert.Equal(Path.GetFileNameWithoutExtension(f), c.Name);
                Assert.Empty(c.Validate(null, SceneLayoutTests.Catalog(), ZeldaDaughter.Core.Data.DataSet.Load(TestPaths.DataRoot).Movement.Terrain.Keys.ToList()));
            }
        }

        [Fact]
        public void G1_scene_has_the_april_iso_camera()
        {
            var c = SceneConfig.Parse(File.ReadAllText(Path.Combine(ScenesDir, "g1-capsule.json")));
            Assert.True(c.Camera.Orthographic);
            Assert.Equal(35f, c.Camera.Pitch);
            Assert.Equal(45f, c.Camera.Yaw);
            Assert.Equal("capsule", c.Hero.Shape);
        }

        [Fact]
        public void Prologue_distances_follow_the_design()
        {
            // §2: «через ~15 секунд ходьбы по дороге — крестьянин… город совсем рядом — в первые минуты».
            var c = SceneConfig.Parse(File.ReadAllText(Path.Combine(ScenesDir, "prologue-grey.json")));
            var walk = ZeldaDaughter.Core.Data.DataSet.Load(TestPaths.DataRoot).Movement.WalkSpeed;
            float Dist(string id)
            {
                var p = c.Objects.Single(o => o.Id == id).Position;
                return (float)System.Math.Sqrt((p.X - c.Hero.Spawn.X) * (p.X - c.Hero.Spawn.X) + (p.Z - c.Hero.Spawn.Z) * (p.Z - c.Hero.Spawn.Z));
            }
            Assert.InRange(Dist("npc_peasant") / walk, 13f, 17f);
            Assert.InRange(Dist("town_gate") / walk, 20f, 60f);
            foreach (var target in new[] { "town_gate", "town_square" }) Assert.Contains(c.Objects, o => o.Id == target);
        }

        // --- D-10: the start region (scenes/region.json, generated by tools/gen-region.py) ---

        static SceneConfig Region() => SceneConfig.Parse(File.ReadAllText(Path.Combine(ScenesDir, "region.json")));

        static float Walk() => ZeldaDaughter.Core.Data.DataSet.Load(TestPaths.DataRoot).Movement.WalkSpeed;

        /// <summary>Metres along the main road from its start to the point on it nearest to (x, z); lateral = distance to the road.</summary>
        static (float Along, float Lateral) OnRoad(SceneConfig c, float x, float z)
        {
            var pts = c.Paths.Single(p => p.Id == "road_main").Points;
            float best = float.MaxValue, bestAlong = 0, acc = 0;
            for (int i = 0; i + 1 < pts.Count; i++)
            {
                float vx = pts[i + 1].X - pts[i].X, vz = pts[i + 1].Z - pts[i].Z, len = (float)System.Math.Sqrt(vx * vx + vz * vz);
                float t = System.Math.Max(0f, System.Math.Min(1f, ((x - pts[i].X) * vx + (z - pts[i].Z) * vz) / (len * len)));
                float px = pts[i].X + vx * t - x, pz = pts[i].Z + vz * t - z, d = (float)System.Math.Sqrt(px * px + pz * pz);
                if (d < best) { best = d; bestAlong = acc + len * t; }
                acc += len;
            }
            return (bestAlong, best);
        }

        static float RoadLength(SceneConfig c) => OnRoad(c, 1e6f, 0f).Along;

        [Fact]
        public void Region_distances_follow_the_design()
        {
            // §2 «Пролог»: крестьянин ~15 с от спавна; город — в первые минуты; §2 «Размер»: край до края 2–3 мин.
            var c = Region();
            float walk = Walk();
            var peasant = c.Objects.Single(o => o.Id == "npc_peasant").Position;
            var spawn = c.Hero.Spawn;
            Assert.InRange((float)System.Math.Sqrt((peasant.X - spawn.X) * (peasant.X - spawn.X) + (peasant.Z - spawn.Z) * (peasant.Z - spawn.Z)) / walk, 13f, 17f);
            float peasantAlong = OnRoad(c, peasant.X, peasant.Z).Along, gate = OnRoad(c, 35f, 0f).Along;
            var gateObj = c.Objects.Single(o => o.Id == "town_gate").Position;
            gate = OnRoad(c, gateObj.X, gateObj.Z).Along;
            Assert.InRange((gate - peasantAlong) / walk, 20f, 75f);           // от крестьянина до ворот — не дольше ~75 с
            float far = c.Objects.Where(o => o.Tags.Contains("poi")).Max(o => o.Position.X);
            Assert.InRange(RoadLength(c) / walk, 120f, 180f);                 // дорога от спавна до дальнего края города
            Assert.True(far <= c.Ground.SizeX / 2);
            foreach (var target in new[] { "town_gate", "town_square", "anchor_bridge", "anchor_glade" }) Assert.Contains(c.Objects, o => o.Id == target);
            // лес и поляна — 15–20 с вглубь от дороги
            var glade = c.Objects.Single(o => o.Id == "anchor_glade").Position;
            var trail = c.Paths.Single(p => p.Id == "trail_glade").Points;
            float len = 0;
            for (int i = 0; i + 1 < trail.Count; i++) len += (float)System.Math.Sqrt((trail[i + 1].X - trail[i].X) * (trail[i + 1].X - trail[i].X) + (trail[i + 1].Z - trail[i].Z) * (trail[i + 1].Z - trail[i].Z));
            Assert.InRange(len / walk, 15f, 20f);
            Assert.True(OnRoad(c, glade.X, glade.Z).Lateral > 30f);
        }

        [Fact]
        public void Region_points_of_interest_every_15_seconds_along_the_road()
        {
            // критерий D-10 №2: соседние точки интереса (тег poi) вдоль главной дороги — не дальше 15 с × скорость шага.
            var c = Region();
            float limit = 15f * Walk();
            var stops = c.Objects.Where(o => o.Tags.Contains("poi")).Select(o => OnRoad(c, o.Position.X, o.Position.Z))
                .Where(a => a.Lateral <= 30f).Select(a => a.Along).OrderBy(a => a).ToList();
            Assert.True(stops.Count >= 20, $"точек интереса у дороги: {stops.Count}");
            stops.Insert(0, 0f);
            stops.Add(RoadLength(c));
            for (int i = 1; i < stops.Count; i++)
                Assert.True(stops[i] - stops[i - 1] <= limit, $"между точками интереса {stops[i - 1]:0.#} и {stops[i]:0.#} м — {(stops[i] - stops[i - 1]) / Walk():0.#} с (> 15)");
        }

        [Fact]
        public void Region_has_the_places_the_data_expects()
        {
            var c = Region();
            var d = ZeldaDaughter.Core.Data.DataSet.Load(TestPaths.DataRoot);
            var ids = c.Objects.ToDictionary(o => o.Id);
            foreach (var key in d.Npcs.Npcs.Keys) Assert.True(ids.ContainsKey("npc_" + key) && ids["npc_" + key].Tags.Contains("npc"), "npc_" + key);
            foreach (var a in d.Npcs.Npcs.SelectMany(n => n.Value.Schedule).Select(s => s.Anchor).Distinct()) Assert.True(ids.ContainsKey(a), a);
            foreach (var m in d.Map.Marks.Values) Assert.True(ids.ContainsKey(m.Object), m.Object);
            foreach (var z in d.Night.Zones) Assert.True(ids.ContainsKey(z), z);
            Assert.Equal("locket", ids["pickup_locket"].Item);
            Assert.Contains(c.Objects, o => o.Tags.Contains("bed"));
            Assert.Contains(c.Objects, o => o.Tags.Contains("smelter") && o.Tags.Contains("station"));
            Assert.Contains(c.Objects, o => o.Tags.Contains("anvil") && o.Tags.Contains("station"));
            Assert.Contains(c.Objects, o => o.Tags.Contains("enemy_spawn") && o.Tags.Contains("enemy_boar"));
            Assert.Contains(c.Objects, o => o.Tags.Contains("campfire") && o.Tags.Contains("rest_point"));
            Assert.True(c.Objects.Count(o => o.Tags.Contains("grass_cell")) >= 40);
            Assert.True(c.Zones.Count(z => z.Tags.Contains("mud")) >= 2);
            foreach (var item in new[] { "stick", "stone", "flint", "berries", "herbs", "healing_herbs", "special_herb", "ore", "firewood", "cloth", "short_stick" })
                Assert.Contains(c.Objects, o => o.Item == item);
            foreach (var k in new[] { "tavern", "smithy", "herb_house", "house_a", "house_b", "house_c", "hut", "gatehouse" }) Assert.True(ids.ContainsKey(k), k);
            Assert.True(ids.ContainsKey("fountain") && ids.ContainsKey("shop_stall"));
            // регион — первая сцена сборки, серый пролог в демо не входит
            Assert.True(c.Build.Include);
            Assert.Equal(0, c.Build.Order);
            Assert.Equal("slot", c.Save.Slot);
        }

        [Fact]
        public void Region_keeps_the_road_and_the_bridge_free()
        {
            var c = Region();
            var cat = SceneLayoutTests.Catalog();
            var road = c.Paths.Single(p => p.Id == "road_main").Points;
            var samples = new System.Collections.Generic.List<(float X, float Z)>();
            for (int i = 0; i + 1 < road.Count; i++)
            {
                float vx = road[i + 1].X - road[i].X, vz = road[i + 1].Z - road[i].Z, len = (float)System.Math.Sqrt(vx * vx + vz * vz);
                for (float t = 0; t < len; t += 0.5f) samples.Add((road[i].X + vx * t / len, road[i].Z + vz * t / len));
            }
            foreach (var o in c.Objects.Where(o => !string.IsNullOrEmpty(o.Model) && o.Collide != false))
            {
                var def = cat.Get(o.Model!);
                if (def.Collider.Kind == "none" || def.IsComposite) continue;
                var b = cat.Bounds(o.Model!);
                double a = o.Rotation.Y * System.Math.PI / 180.0;
                float lx = b.CenterX * o.Scale.X, lz = b.CenterZ * o.Scale.Z;
                var rect = new Area { Shape = "rect", Center = new Pt(o.Position.X + lx * (float)System.Math.Cos(a) + lz * (float)System.Math.Sin(a), o.Position.Z - lx * (float)System.Math.Sin(a) + lz * (float)System.Math.Cos(a)),
                    Size = new Pt(b.SizeX * o.Scale.X, b.SizeZ * o.Scale.Z), Rotation = o.Rotation.Y };
                foreach (var s in samples) Assert.True(rect.SignedDistance(s.X, s.Z) > 0.5f, $"{o.Id} стоит на главной дороге у ({s.X:0.#}; {s.Z:0.#})");
            }
            foreach (var p in Scatterer.Generate(c, cat).Where(p => p.Collide))
                foreach (var s in samples) Assert.True((p.X - s.X) * (p.X - s.X) + (p.Z - s.Z) * (p.Z - s.Z) > 1.2f * 1.2f, $"{p.Id} ({p.ModelId}) на главной дороге у ({s.X:0.#}; {s.Z:0.#})");
        }

        [Fact]
        public void Region_scatter_is_deterministic()
        {
            var cat = SceneLayoutTests.Catalog();
            Assert.Equal(Scatterer.Digest(Scatterer.Generate(Region(), cat)), Scatterer.Digest(Scatterer.Generate(Region(), cat)));
        }

        [Fact]
        public void Prologue_grey_is_not_in_the_demo_build()
        {
            var all = Directory.GetFiles(ScenesDir, "*.json").Select(f => SceneConfig.Parse(File.ReadAllText(f))).ToList();
            var list = SceneConfig.BuildList(all);
            Assert.Equal("region", list[0]);
            Assert.DoesNotContain("prologue-grey", list);
        }

        [Fact]
        public void Pickup_items_exist()
        {
            var items = ZeldaDaughter.Core.Data.DataSet.Load(TestPaths.DataRoot).Items;
            foreach (var f in Directory.GetFiles(ScenesDir, "*.json"))
                foreach (var o in SceneConfig.Parse(File.ReadAllText(f)).Objects.Where(o => o.Item != null))
                    Assert.True(items.ContainsKey(o.Item!), $"{Path.GetFileName(f)}: {o.Id} → {o.Item}");
        }

        [Fact]
        public void Problems_are_named()
        {
            var c = SceneConfig.Parse("{\"name\":\"t\",\"ground\":{\"sizeX\":10,\"sizeZ\":10},\"camera\":{\"pitch\":35,\"distance\":20,\"size\":8}," +
                "\"hero\":{\"shape\":\"capsule\"},\"objects\":[{\"id\":\"a\",\"shape\":\"cube\",\"position\":{\"x\":50}}," +
                "{\"id\":\"a\",\"shape\":\"blob\"},{\"id\":\"b\",\"shape\":\"cube\",\"prefab\":\"x.prefab\"},{\"id\":\"c\",\"prefab\":\"missing.prefab\",\"color\":\"red\"}]}");
            var p = c.Validate(prefab => prefab != "missing.prefab");
            Assert.Contains(p, x => x.Contains("'a'") && x.Contains("за краем"));
            Assert.Contains(p, x => x.Contains("'a'") && x.Contains("повтор"));
            Assert.Contains(p, x => x.Contains("blob"));
            Assert.Contains(p, x => x.Contains("'b'") && x.Contains("ровно один"));
            Assert.Contains(p, x => x.Contains("missing.prefab"));
            Assert.Contains(p, x => x.Contains("'c'") && x.Contains("цвет"));
        }

        static SceneConfig Cfg(string name, bool include, int order) =>
            SceneConfig.Parse($"{{\"name\":\"{name}\",\"build\":{{\"include\":{(include ? "true" : "false")},\"order\":{order}}}}}");

        [Fact]
        public void Build_list_is_ordered_by_config_and_skips_excluded_scenes()
        {
            var list = SceneConfig.BuildList(new[] { Cfg("b", true, 2), Cfg("test", false, 0), Cfg("a", true, 0), Cfg("c", true, 1) });
            Assert.Equal(new[] { "a", "c", "b" }, list);
        }

        [Fact]
        public void Build_list_refuses_two_scenes_with_the_same_order()
        {
            Assert.Throws<System.InvalidOperationException>(() => SceneConfig.BuildList(new[] { Cfg("a", true, 0), Cfg("b", true, 0) }));
        }

        [Fact]
        public void Real_build_list_starts_with_the_region_and_has_no_test_capsule()
        {
            var all = Directory.GetFiles(ScenesDir, "*.json").Select(f => SceneConfig.Parse(File.ReadAllText(f)));
            var list = SceneConfig.BuildList(all);
            Assert.Equal("region", list[0]);
            Assert.DoesNotContain("g1-capsule", list);
        }

        [Fact]
        public void Test_capsule_does_not_save_and_the_prologue_has_a_slot()
        {
            var g1 = SceneConfig.Parse(File.ReadAllText(Path.Combine(ScenesDir, "g1-capsule.json")));
            var pro = SceneConfig.Parse(File.ReadAllText(Path.Combine(ScenesDir, "prologue-grey.json")));
            Assert.True(string.IsNullOrEmpty(g1.Save.Slot));
            Assert.False(string.IsNullOrEmpty(pro.Save.Slot));
        }
    }
}
